.PHONY: child-wait
child-wait:
	cargo run --bin child-wait

.PHONY: child-wait-busy-loop
child-wait-busy-loop:
	cargo run --bin child-wait-busy-loop

.PHONY: child-wait-sig-handler
child-wait-sig-handler:
	cargo run --bin child-wait-sig-handler

.PHONY: grandchild-wait-subrepear
grandchild-wait-subrepear:
	cargo run --bin grandchild-wait-subrepear